### ISSUE TITLE
crash if attempts to block no-longer-existing user, e.g. elonmusksama

### ISSUE THREAD

**Issue by lahosken** [travisbrown/octocrabby#17]
Apparently sometimes github users go away and thusly can't be blocked. I ran `target/release/crabby -vvv -t [redacted] block-users < jerks.csv`

...where `jerks.csv` was generated via `list-pr-contributors -r rms-support-letter/rms-support-letter.github.io` . It crashed 

```
23:41:13 [WARN] eligiobz was already blocked
23:41:13 [WARN] eliphatfs was already blocked
Error: GitHub { source: GitHubError { documentation_url: "https://docs.github.com/rest/reference/users#block-a-user", errors: None, message: "Not Found" }, backtrace: Backtrace(   0: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```

I can work around by editing `jerks.csv` , no problem. But it'd be nice if this crash were just a warning, yep.

**Comment by travisbrown** [comment]
Thanks for the report! I believe this issue should have been fixed in #7. I just confirmed that on current `main` the `list-blocks` command doesn't crash on a non-existent username (although it does log "was already blocked", which is a bug that I'll fix now).

(If you update to the latest `main` you'll also get #11, which speeds things up a lot if you're running the command incrementally on a repo.)
